sudo: required
dist: trusty

language: C++

script:
  - cd TcpServer/
  - mkdir build
  - cd build
  - cmake ..
  - make

  - cd ../..

  - cd TcpClient/
  - mkdir build
  - cd build
  - cmake ..
  - make
